// Dados centralizados dos checklists
export const checklists = [
  {
    categoria: "Desenvolvimento Web",
    itens: [
      "\n--- Imagens ---",
      "Adicionar alt para imagens, botões-imagem, gráficos e imagens de mapas com pontos de acesso.",
      "Adicionar alt='' para imagens decorativas que não tem significado.",
      "Incluir a descrição no alt para imagens que contêm texto.",
      "Garantir contraste adequado entre texto da imagem e plano de fundo.",
      "Evitar textos com fontes muito pequenas dentro da imagem.",
      "\n--- Vídeos ---",
      "Adicionar legendas para áudio em vídeos existentes.",
      "Evitar conteúdo com flashes (gatilhos para convulsões) ou manter abaixo dos limites.",
      "Adicionar botão de controle de legenda e audiodescrição.",
      "\n--- Controles ---",
      "Adicionar href para links.",
      "Adicionar underline nos links.",
      "Adicionar estados de foco em campos de entrada, botões, e elementos interativos.",
      "Adicionar type='button' nos botões.",
      "Adicionar skip-link (link para pular) para o conteúdo principal.",
      "Identifique e comunique links que abrem em uma nova guia ou janela.",
      "Garantir que todos os botões tenham nome acessível por leitores de tela.",
      "\n--- Formulário ---",
      "Adicionar label para os campos de entradas associadas ao elemento correspondente.",
      "Adicionar <fieldset> e <legend> para seção no formulário.",
      "Adicionar autocomplete para campos de entrada.",
      "Exibir errors (erros) de entrada acima do formulário, após envio.",
      "Adicionar aria-describedby para os campos de entrada.",
      "Exibir mensagens de erro e sucesso não só visualmente.",
      "Utilizar validação em tempo real acessível para indicar campos obrigatórios ou incorretos.",
      "\n--- Mídia ---",
      "Impedir autoplay para vídeos e áudios.",
      "Adicionar type para botões e entradas.",
      "Adicionar pausa para todas as mídias.",
      "Adicionar transcrição para áudios.",
      "\n--- Semântica ---",
      "Uso de elementos nativos HTML.",
      "Fluxo contínuo e lógico.",
      "Tem descrições que podem ser facilmente compreendidas.",
      "Tem a semântica correta.",
      "É objetivo nos rótulos.",
      "\n--- Texto ---",
      "Evitar o uso de textos dentro de imagens.",
      "Redimensiona os textos na página, aumentando o zoom em até 200%.",
      "Alturas das fontes não é fixa.",
      "\n--- Teclado ---",
      "Funcionalidades da página web estão disponíveis por teclado.",
      "Quando se tem o mouseover é permitido o uso de teclado.",
      "Foco visível remova elementos focalizáveis invisíveis.",
      "Adicione o .hover, .focus { } para tornar o foco visível.",
      "Permite/visa o uso de Atalhos de teclado como o TAB.",
      "Primeiro item interativo da página é um link para o conteúdo principal.",
      "Garantir ordem lógica de navegação por teclado.",
      "\n--- Título ---",
      "A hierarquia de conteúdo da página é definida por sua lógica não pelo tamanho do texto.",
      "Use elementos de título h1 h2 h3 para apresentar o conteúdo.",
      "Não pular níveis lógicos.",
      "Toda página contém um título h1 descrevendo a página.",
      "\n--- Tabela ---",
      "Use o table para elementos em formato de tabela.",
      "Insira cabeçalhos para explicar os dados, use th com scope correto.",
      "Use o caption elemento para fornecer um título para a tabela.",
      "Não usar tabelas para layout.",
      "\n--- Modais ---",
      "Deve ser fácil fechar.",
      "Permitir o uso da tecla escape ESC.",
      "A interação é uma tarefa simples.",
      "Evita modais em tela cheia.",
      "Não abrir um modal a partir de outro modal.",
      "Gerenciar foco corretamente dentro do modal.",
      "\n--- Dispositivo Móvel e tocável ---",
      "O site pode ser rotacionado para qualquer orientação.",
      "Impedir rolagem horizontal.",
      "Garantir que botões e links possam ser ativados facilmente.",
      "Garantir espaço suficiente entre elementos interativos.",
      "Garantir acessibilidade para gestos de toque.",
      "\n--- Ferramentas e extras ---",
      "Permitir pausar, parar ou ocultar conteúdo em movimento.",
      "Usar Breadcrumbs informando a localização atual nas páginas.",
      "Colocar página ou área de esclarecimento de dúvidas e dicas de acessibilidade.",
      "Áreas clicáveis com no mínimo 44px (pixels) de altura e 44px de largura.",
      "No caso de captcha garanta que seja simples de entender e tenha alternativas para pessoas com deficiência.",
      "Incluir um campo de busca.",
      "Indicar idioma principal da página com lang='' na tag <html>."
    ]
  },
  {
    categoria: "Geração de Conteúdo",
    itens: [
      "\n--- Termos ---",
      "Sempre utilize o termo 'pessoas com deficiência' (PCD) e depois complemente: visual, física, intelectual, múltipla, pessoa surda, pessoa cega, usuária de cadeira de rodas (cadeirante), tetraplégica, paraplégica, pessoa com nanismo, com baixa visão, pessoa autista, disléxica, neurodiversa ou neurodivergente.",
      "Evite termos capacitistas (ex: 'portador', 'sofre de', 'deficiente', 'normal').",
      "Prefira termos neutros e respeitosos que não infantilizem ou romantizem a deficiência.",
      "Sempre atualize a terminologia conforme as diretrizes oficiais (ex: ONU, ABNT, MEC, Movimento PcD).",
      "\n--- Textos ---",
      "Usar textos descomplicados e objetivos.",
      "Usar de palavras conhecidas.",
      "Evitar figuras de linguagem e frases com 'senso de urgência'.",
      "Usar pontuação adequada.",
      "Evitar frases extensas (ideal é ter de 15 a 20 palavras).",
      "Usar preferencialmente a ordem direta nas orações.",
      "Evitar o uso de jargões técnicos ou explicar quando inevitáveis.",
      "Dar preferência a voz ativa e evitar ambiguidade.",
      "Criar títulos e subtítulos explicativos e hierarquizados.",
      "\n--- Descrição de Imagens ---",
      "Identificar o tipo de imagem e personagem (foto, ilustração, mapa, gráfico... e 'o que/quem').",
      "Localizar (onde).",
      "Descrever a ação (o que faz, como faz).",
      "Referenciar.",
      "Descrever expressões faciais ou tons emocionais relevantes.",
      "\n--- Descrição de Imagens Complexas ---",
      "Posicionar gráfico, quadrinhos, quadros e outras imagens complexas em um local separado.",
      "Descrição sucinta no texto alternativo.",
      "Oferecer versão textual equivalente da informação visual.",
      "\n--- Ícones ---",
      "Adicionar iconografia.",
      "Adicionar ícone e texto.",
      "Adicionar texto alternativo para ícones clicáveis.",
      "Descrever no texto alternativo, quando necessário usá-lo, a ação da pessoa usuária e para onde será direcionada.",
      "Garantir que os ícones sejam reconhecíveis em escala reduzida.",
      "\n--- Mídias de Vídeo ---",
      "Adicionar descritivo curto para vídeos.",
      "Optar por legendas: Open Caption e Closed Caption para vídeos.",
      "Incluir audiodescrição sincronizada ou alternativa.",
      "Disponibilizar roteiro do vídeo em texto.",
      "Incluir janela de Libras, quando possível.",
      "\n--- Autodescrição ---",
      "Adicionar autodescrição no roteiro dos vídeos.",
      "Apresentar a autodescrição no início, antes da fala principal.",
      "Garantir que a autodescrição seja coerente com o propósito do conteúdo.",
      "\n--- Podcasts ---",
      "Transcrever o conteúdo do episódio.",
      "Incluir além das partes faladas, como sons de fundos, efeitos sonoros, quem está falando etc.",
      "Inserir um avatar na página falada para a interpretação do texto transcrito para Libras.",
      "Considerar também formato de vídeo.",
      "Indicar, quando necessário, pausas, risos ou mudanças de entonação relevantes.",
      "\n--- Hashtags e Emojis ---",
      "Em hashtags, utilize a primeira letra de cada palavra em maiúsculas para que leitores possam identificar palavras corretamente.",
      "Não abusar de emojis, pois nem sempre sua descrição é suficiente para um bom entendimento.",
      "Evitar mensagens compostas apenas por emojis.",
      "\n--- Hiperlinks ---",
      "Descrição de links e botões devem ser compreensíveis de maneira isolada.",
      "Evite links compostos apenas por ícones ou palavras genéricas."
    ]
  },
  {
    categoria: "Gestão de Projetos",
    itens: [
      "\n--- Personas ---",
      "Pessoas com Deficiência Visual (cegueira, baixa visão, daltonismo ou deficiência cromática)",
      "Pessoas com Deficiência Física (fraqueza, tremores, movimentos involuntários, paralisia, limitações da sensação, dor que impede movimento, ausência de membros)",
      "Pessoas com Deficiência Auditiva (surdez, baixa audição, surdocegueira)",
      "Pessoas com Deficiência na Fala (dificuldade para falar, volume insuficiente, gagueira, mudez)",
      "Pessoas Neurodiversas (dificuldades de diferentes graus para ver, escutar, falar, compreender e interagir socialmente)",
      "Pessoas com Múltiplas Deficiências (combinação de duas ou mais deficiências anteriores)",
      "Possíveis limitações decorrentes do envelhecimento (que podem ser de um ou mais grupos de deficiências)",
      "Pessoas com analfabetismo (analfabetismo digital e funcional níveis 1, 2 e 3)",
      "Pessoas com Baixa Conectividade ou Uso de Dados Limitado (usuários com acesso precário à internet, planos limitados ou instabilidade de conexão)",
      "Usuários com Dispositivos Antigos ou de Baixo Desempenho (pessoas com smartphones ou computadores mais antigos, pouco armazenamento ou memória limitada)",
      "Pessoas com Baixo Letramento Digital (usuários com pouca familiaridade com tecnologia, interfaces ou navegação digital)",
      "Pessoas Idosas (mesmo sem deficiência diagnosticada (usuários com possíveis limitações leves de visão, audição, cognição ou motricidade fina)",
      "Cuidadores ou Acompanhantes (usuários que acessam o sistema em nome de outras pessoas (idosos, PCDs, crianças))",
      "Pessoas em Situações de Estresse ou Urgência (usuários que acessam o sistema em momentos críticos ou sob pressão)",
      "Pessoas com Barreiras Linguísticas (pessoas não fluentes na língua do sistema)",
      "Usuários de Diferentes Contextos Culturais (diferenças em símbolos)",
      "Pessoas com Restrições Temporárias (usuários afetados por condições transitórias (ex: braço imobilizado, ambiente escuro, sem óculos))",
      "\n--- Conscientização ---",
      "Quantidade de pessoas no mundo com algum tipo de deficiência.",
      "Quantidade de pessoas no Brasil com algum tipo de deficiência, segundo IBGE.",
      "Natureza da deficiência: congênita, hereditária, adquirida, temporária.",
      "Grupos mais comuns de tipos de deficiência.",
      "Quanto custa a acessibilidade?",
      "Quanto tempo a mais o projeto precisará para implementar acessibilidade?",
      "Quantas pessoas com deficiência vão usar meu aplicativo ou acessar meu sítio de Internet?",
      "Pessoas cegas compram online?",
      "Pessoas surdas assistem vídeos?",
      "Pessoas tetraplégicas usam smartphone?",
      "Legislação: A Convenção sobre os Direitos das Pessoas com Deficiência Comentada.",
      "Legislação: PORTARIA Nº 3, DE 7 DE MAIO DE 2007.",
      "Análise de mercado de software de acessibilidade digital.",
      "Requisitos não funcionais incluem critérios de acessibilidade.",
      "A acessibilidade beneficia outros grupos além das pessoas com deficiência.",
      "A acessibilidade digital é fator de inovação, reputação e vantagem competitiva.",
      "\n--- Planejamento ---",
      "Atividades bem delineadas, cronogramas e atribuições de responsabilidade relacionadas à acessibilidade?",
      "Tarefas com critérios de sucesso que atendam pelo menos os níveis A e AA, segundo a documentação de acessibilidade (WCAG)?",
      "Acessibilidade foi definida como requisito essencial desde a fase de concepção do projeto?",
      "As partes interessadas foram informadas da importância da acessibilidade?",
      "Há profissionais com conhecimento em acessibilidade na equipe ou consultores designados?",
      "O orçamento contempla recursos para implementar e testar acessibilidade?",
      "Capacitação Contínua: Oferta de treinamentos regulares sobre acessibilidade digital para a equipe?",
      "Monitoramento e Avaliação: Implementação de processos para avaliar e monitorar a acessibilidade ao longo do projeto?"
    ]
  },
  {
    categoria: "Design",
    itens: [
      "\n--- Aparência ---",
      "Adicionar instrução que não dependa exclusivamente da cor.",
      "Adicionar informação (como gráficos e diagramas) que não dependa exclusivamente da cor.",
      "Tamanho do texto ajustável para permitir ampliação.",
      "Descrever os controles pelo nome, não apenas pela aparência ou localização.",
      "Garantir que dicas visuais significativas atinjam 3:1 em relação ao fundo.",
      "Fazer com que as linhas de texto se ajustem ao viewport.",
      "Oferece uma opção de alto contraste (dark-mode) de suas páginas web e aumento de fontes.",
      "Parágrafos com no máximo 80 caracteres por linha.",
      "Evita o uso de textos longos em caixa alta ou condensados.",
      "Evita o alinhamento justificado.",
      "Fontes são fluidas e de fácil entendimento.",
      "Toma o devido cuidado com display:none e visibility:hidden para os recursos de tecnologia assistiva.",
      "Preferir botões com texto e ícone. E botões apenas com ícones tem o nome acessível.",
      "Tipografia legível com fontes de fácil leitura.",
      "Tipografia legível com fontes de tamanho adequado.",
      "Evita elementos visuais muito próximos, dificultando toque ou leitura.",
      "Evita dependencia de instruções posicionais, como 'clique no botão à direita'.",
      "Evita textos animados, cintilantes ou movimentação constante.",
      "\n--- Animação ---",
      "Evitar conteúdo que pisque, ou mantenha-o abaixo dos limites.",
      "Permitir que os usuários controlem as alterações de conteúdo que ocorrem em paralelo com outro conteúdo.",
      "Toda a animação deve obedecer à prefers-reduced-motion consulta de mídia.",
      "Toda animação possui descrição em áudio, para pessoas cegas.",
      "Evitar loops infinitos em vídeos ou gifs animados.",
      "Evitar transições rápidas ou abruptas, que podem causar desconforto sensorial.",
      "\n--- Contraste de Cores ---",
      "Verificar o contraste de todo texto tamanho normal.",
      "Verificar o contraste de todo texto tamanho grande.",
      "Verificar o contraste de todos os ícones.",
      "Verificar o contraste das bordas dos elementos de entrada (entrada de texto, botões de opção, caixas de seleção, etc.).",
      "Verificar texto que se sobrepõe a imagens ou vídeos.",
      "Verificar ::selection cores personalizadas.",
      "Verificar o contraste de todo o texto de acordo com o fundo.",
      "Verificar o contraste de todo o texto sob uma imagem.",
      "Verificar uso exclusivo de cores não dependendo apenas de cores para transmitir informações.",
      "Verificar o contraste do layout em conjunto."
    ]
  }
]

// Função para exportar todos os checklists em um arquivo .txt
export function exportAllChecklists() {
  let txt = ""
  checklists.forEach(({ categoria, itens }) => {
    txt += `Categoria: ${categoria}\n`;
    itens.forEach((item, idx) => {
      txt += `- ${item}\n`;
    });
    txt += "\n";
  });

  const blob = new Blob([txt], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "checklists-verificaAAA.txt";
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
} 